chore: fix typescript compilation
- Specify `src/**/*` include pattern in tsconfig (default: `**/*`)
- Enable `resolveJsonModule` compiler option

Addresses the following compilation errors:

```
error TS6059: File '/Users/devon/code/artsy/metaphysics/wallaby.js' is not under 'rootDir' '/Users/devon/code/artsy/metaphysics/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by include pattern '**/*' in '/Users/devon/code/artsy/metaphysics/tsconfig.json'
```

```
src/schema/v2/fields/money.ts:14:27 - error TS2732: Cannot find module 'lib/currency_codes.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```